#!/bin/sh

MIGRATED=`git diff HEAD@{1} --name-only | grep migrate | wc -l`
if [ $MIGRATED -gt 0 ];
then
    echo "########### postmerge: Migrations detected! ############"
fi

CHANGED=`git diff HEAD@{1} --name-only | grep Gemfile.lock | wc -l`
if [ $CHANGED -gt 0 ];
then
    echo "########### postmerge: Gemfile.lock has changed! ############"
fi
